volumes:
  postgres-data:
  redis-data:

networks:
  backend:
  frontend:

x-common-env: &common-env
  HOSTNAME: "0.0.0.0"
  PORT: 3000
  REDIS_URL: redis://redis:6379
  CORE_PUBLIC_URL: http://development.mairie360.fr

# x-depends-on: &depends-on
#   postgres:
#     condition: service_healthy
#   redis:
#     condition: service_healthy

x-healthcheck: &healthcheck
  test: ["CMD", "curl", "-f", "http://localhost:3000"]
  interval: 10s
  timeout: 5s
  retries: 5

x-service: &service-template
  pull_policy: always
  restart: always
  expose:
    - "3000"
  networks:
    - backend
    - frontend
  healthcheck:
    <<: *healthcheck

services:
  postgres:
    image: ghcr.io/mairie360/database:dev-latest
    restart: always
    container_name: mairie360-db-projects-front #change front name
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
      POSTGRES_DB: mairie_360_database
    expose:
      - "5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  liquibase:
    image: ghcr.io/mairie360/liquibase-migrations:dev-latest
    container_name: mairie360-liquibase-projects-front #change front name
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      <<: *common-env
      LIQUIBASE_COMMAND_URL: jdbc:postgresql://postgres:5432/mairie_360_database
      LIQUIBASE_COMMAND_USERNAME: ${DB_USER:-postgres}
      LIQUIBASE_COMMAND_PASSWORD: ${DB_PASSWORD:-password}
      LIQUIBASE_SEARCH_PATH: /liquibase/changelog
    command: >
      --changelog-file=changelog.xml
      update
    networks:
      - backend

  redis:
    image: redis:7.4.8-bookworm
    container_name: mairie360-redis-projects-front #change front name
    restart: always
    expose:
      - "6379"
    volumes:
      - redis-data:/data
    networks:
      - backend
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # core:
  #   container_name: core-projects-front-developpement
  #   image: ghcr.io/mairie360/core-api:dev-1644fa7
  #   ports:
  #     - "3000:3000"
  #   networks:
  #     - backend
  #   dns:
  #     - 8.8.8.8
  #     - 1.1.1.1
  #   environment:
  #     HOST: "0.0.0.0"
  #     PORT: 3000
  #     REDIS_URL: redis://redis:6379
  #     DB_TYPE: postgres
  #     DB_NAME: mairie_360_database
  #     DB_USER: postgres
  #     DB_HOST: postgres
  #     DB_PASSWORD: password
  #     DB_PORT: 5432
  #     PUBLIC_URL: http://core.development.mairie360.fr
  #     JWT_SECRET: b"secret"
  #     JWT_TIMEOUT: 3600
  #   depends_on:
  #     liquibase:
  #       condition: service_completed_successfully
  #     redis:
  #       condition: service_healthy
      
  project-api:
    container_name: project-api-front-projects-developpement
    image: ghcr.io/mairie360/project-api:dev-latest
    ports:
      - "3001:3001"
    networks:
      - backend
    dns:
      - 8.8.8.8
      - 1.1.1.1
    environment:
      HOST: "0.0.0.0"
      PORT: 3001
      REDIS_URL: redis://redis:6379
      DB_TYPE: postgres
      DB_NAME: mairie_360_database
      DB_USER: postgres
      DB_HOST: postgres
      DB_PASSWORD: password
      DB_PORT: 5432
      PUBLIC_URL: http://core.development.mairie360.fr
      JWT_SECRET: b"secret"
      JWT_TIMEOUT: 3600
    depends_on:
      liquibase:
        condition: service_completed_successfully
      redis:
        condition: service_healthy
  
  #add other apis if needed

  bff-project:
    container_name: bff-project-projects-front
    image: ghcr.io/mairie360/bff-project:dev-latest
    ports:
      - "4001:4001"
    networks:
      - backend
      - frontend
    environment:
      CORE_API_URL: "core" 
      CORE_API_PORT: 3000
      PROJECT_API_URL: "project-api" 
      PROJECT_API_PORT: 3001
      PORT: 4001
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4001/health"]
      interval: 10s
      timeout: 5s
      retries: 3
  
  projects-front: # Ton application React
    container_name: projects-front-developpement
    build:
      context: .
      dockerfile: development.Dockerfile
      secrets:
        - NODE_AUTH_TOKEN
    ports:
      - "5001:3000" # On map le 3000 interne sur 3001 pour éviter le conflit avec 'core'
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
        - action: rebuild
          path: package.json
    secrets:
      - NODE_AUTH_TOKEN
    environment:
      <<: *common-env
      PORT: 3000
      # Force React/Vite à surveiller les fichiers correctement dans Docker
      WATCHPACK_POLLING: "true" 
      CHOKIDAR_USEPOLLING: "true"
    networks:
      - frontend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 10s
      retries: 3
        
secrets:
  NODE_AUTH_TOKEN:
    environment: NODE_AUTH_TOKEN