name: Project Web Service CICD

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: write
  packages: write
  id-token: write

jobs:
  CICD:
    uses: mairie360/CICD/.github/workflows/BFFs-cicd.yml@feat/mair-7-add-cicd-for-bffs
    with:
      package_name: "projects-front"
      node_version: 23
    secrets: inherit